# Общие параметры тестирования
test_duration: 30  # длительность каждого теста в секундах

# Параметры для полного цикла тестирования
test_combinations:
  video_protocols:
    - HTTP
    - RTSP
    - UDP
    - WebRTC
  control_protocols:
    - HTTP
    - UDP
    - WebSocket
  resolutions:
    - QQVGA
    - QVGA
    - VGA
    - SVGA
    - XGA
    - SXGA
    - UXGA
  qualities:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60

# Параметры WiFi (можно переопределить через .env)
wifi:
  ssid: ${WIFI_SSID}
  password: ${WIFI_PASSWORD}
  connection_timeout: 30     # Seconds to wait for WiFi connection

# Paths for results
results_dir: "results"
video_dir: "results/video"
logs_dir: "results/logs"
metrics_dir: "results/metrics" 