# Общие параметры тестирования
test_duration: 30  # длительность каждого теста в секундах

# Поддерживаемые протоколы
video_protocols:
  - HTTP
  - RTSP
  - UDP
  - WebRTC

control_protocols:
  - HTTP
  - UDP
  - WebSocket

# Параметры камеры
camera_resolutions:
  QQVGA: [160, 120]
  QVGA: [320, 240]
  VGA: [640, 480]
  SVGA: [800, 600]
  XGA: [1024, 768]
  SXGA: [1280, 1024]
  UXGA: [1600, 1200]

# Параметры для полного цикла тестирования
test_combinations:
  control_protocols:
    - HTTP
    - UDP
    - WebSocket
  resolutions:
    - QQVGA
    - QVGA
    - VGA
    - SVGA
    - XGA
    - SXGA
    - UXGA
  qualities:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60

# Параметры WiFi (можно переопределить через .env)
wifi:
  ssid: ${WIFI_SSID}
  password: ${WIFI_PASSWORD}
  connection_timeout: 30     # Seconds to wait for WiFi connection

# Paths for results
results_dir: "results"
video_dir: "results/video"
logs_dir: "results/logs"
metrics_dir: "results/metrics" 