[tool.ruff]
# Exclude files and directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist"
]

# Same as Black.
target-version = "py38"

[tool.ruff.lint]
# Enable Pyflakes (`F`), pycodestyle (`E`), and import sorting (`I`)
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "PT", "RET", "SIM"]
# Ignore line length violations
ignore = ["E501"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["run_tests"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.pydocstyle]
convention = "google" 