name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Cache virtualenv
      uses: actions/cache@v2
      with:
        path: |
          .venv
          ~/.cache/pip
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format python3-venv
    
    - name: Setup virtual environment
      run: |
        make venv
    
    - name: Run Python linting
      run: |
        make pylint
    
    - name: Run C++ linting
      run: |
        make lint
    
    - name: Check code formatting
      run: |
        make format
        git diff --exit-code || (echo "Code formatting issues found. Run 'make format' locally" && exit 1)
    
    - name: Run tests
      run: |
        make test
    
    - name: Build firmware
      run: |
        make build
    
    - name: Generate coverage report
      run: |
        .venv/bin/pytest tests/ -v --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true 